# Label configuration for PR Labeler
# https://github.com/actions/labeler
# Requires a workflow that runs actions/labeler.
documentation:
  - changed-files:
      - any-glob-to-any-file: ['Documentation/**/*', '**/*.md', 'context/**/*']
tests:
  - changed-files:
      - any-glob-to-any-file: ['Tests/**/*', 'Build/phpunit/**/*']
ci:
  - changed-files:
      - any-glob-to-any-file: ['.github/**/*', 'Build/**/*', '.gitlab-ci.yml']
dependencies:
  - changed-files:
      - any-glob-to-any-file: ['composer.json', 'composer.lock']
configuration:
  - changed-files:
      - any-glob-to-any-file: ['Configuration/**/*', 'ext_*.php', 'ext_*.txt', 'ext_*.sql', 'composer.json']
